
#define AIMBOT_TEXT  "AIMBOT"

#define	A_aimbot "aimbot"
#define	A_autoaimbot "autoaimbot"
#define	A_aimbotenemy "aimbotenemy"
#define	A_aimbotteam "aimbotteam"
#define	A_aimkey "aimkey"
#define	A_fov "fov"
#define	A_lock "lock"
#define	A_aimsmooth "aimsmooth"
#define	A_drawfov "drawfov"
#define	A_aimstrongsmooth "aimstrongsmooth"
#define	A_hitboxbone "hitboxbone"
#define	A_pointscalex "pointscalex"
#define	A_pointscaley "pointscaley"

#define ESP_TEXT  "ESP"
#define	E_enableesp "enableesp"
#define	E_espboxtype "espboxtype"
#define E_esphealthbartype "esphealthbartype"
#define E_espvehiclemode "esphealthbartype"
#define E_distancetoplayer "distancetoplayer"
#define E_enemyboxes "enemyboxes"
#define E_enemydistance "enemydistance"
#define E_enemyfilledbox "enemyfilledbox"
#define E_enemyhealth "enemyhealth"
#define E_enemyNames "enemyNames"
#define E_enemyskeleton "enemyskeleton"
#define E_enemysnaplines "enemysnaplines"
#define E_teamboxes "teamboxes"
#define E_teamdistance "teamdistance"
#define E_teamfilledbox "teamfilledbox"
#define E_teamhealth "teamhealth"
#define E_teamnames "teamnames"
#define E_teamskeleton "teamskeleton"
#define E_teamsnaplines "teamsnaplines"
#define E_teamvisskeleton "teamvisskeleton"
#define E_enemyvehicle "enemyvehicle"
#define E_enemyvehicledmg "enemyvehicledmg"
#define E_enemyvehicleName "enemyVehicleName"
#define E_teamvehicle "teamVehicle"
#define E_teamvehicledmg "teamvehicledmg"
#define E_teamvehicleName "teamvehicleName"
#define E_espvehiclemode "espvehiclemode"
#define E_filledboxAlpha "teamfilledboxAlpha"


#define MISC_TEXT  "MISC"
#define M_radarteam "radarteam"
#define M_radarwindow "radarwindow"
#define M_radralpha "radralpha"
#define M_radarzoom "radarzoom"
#define M_distancetoplayer "distancetoplayer"


#define M_radarenemy "radarenemy"
#define M_teamvehicle "teamvehicle"
#define M_enemyvehicle "enemyvehicle"

#define M_crosshairtype "crosshairtype"
#define M_size "size"
#define M_stroke "stroke"

#define M_autospot "autospot"
#define M_autospotkey "autospotkey"

#define MENU_TEXT "MENU"
#define M_iVisualssubTab "ivisualssubtab"
#define M_thame "thame"

#define	COLORS_TEXT "COLORS"
#define	C_teamtolor "teamtolor"
#define C_teamcolorid "teamcolorid"
#define	C_occludedenemycolor "occludedenemycolor"
#define	C_visibleenemycolor "visibleenemycolor"
#define	C_teamlinecolor "teamlinecolor"
#define	C_vislinecolor "vislinecolor"
#define	C_unvislinecolor "unvislinecolor"
#define	C_teamskeleton "teamskeleton"
#define	C_visskeleton "visskeleton"
#define	C_unvisskeleton "unvisskeleton"
#define	C_teamfiledboxcolor "teamfiledboxcolor"
#define	C_visfiledboxcolor "visfiledboxcolor"
#define	C_unvisfiledboxcolor "unvisfiledboxcolor"
#define	C_teamdistancecolor "teamdistancecolor"
#define	C_visdistancecolor "visdistancecolor"
#define	C_unvisdistancecolor "unvisdistancecolor"
#define	C_teamnamecolor "teamnamecolor"
#define	C_visnamecolor "visnamecolor"
#define	C_unvisnamecolor "unvisnamecolor"
#define	C_vehiclenamecolor "vehiclenamecolor"
#define	C_vehiclecolor "vehiclecolor"
#define	C_radarteam "radarteam"
#define	C_visradarenemy "visradarenemy"
#define	C_unvisradarenemy "unvisradarenemy"
#define	C_vehicleradar "vehicleradar"
#define	C_crosshair "crosshair"
